format = """
$username\
$hostname\
$directory\
$git_branch\
$git_status\
$fill\
$nodejs\
$python\
$cmd_duration\
$jobs\
$time\
$line_break\
$character

"""

[fill]
symbol = " "

[git_branch]
format ="[[$symbol](bold green)$branch(:$remote_branch)]($style) "

[git_status]
style = "bold white"
conflicted = "[⚑](bold red)"
ahead = "[⇡](bold cyan)"
behind = "[⇣](bold red)"
diverged = "[⚡︎](bold purlple)"
untracked = "[?](bold red)"
stashed = '[\$](bold yellow)'
modified= "[!](bold yellow)"
staged = "[+](bold green)"
renamed = "[»](bold white)"
deleted = "[✘](bold red)"

[time]
disabled = false
format = 'at [$time]($style) '
time_format = "%R %P"
use_12hr = true

[nodejs]
format ="[$symbol($version )]($style)"

[directory]
home_symbol = ""
truncation_length = 2
truncation_symbol = ".../"